services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - USER_ID=${UID}
        - GROUP_ID=${GID}

    user: "${UID}:${GID}"

    volumes:
      - ~/.gitconfig:/home/iguana/.gitconfig
      - ~/.gradle:/home/iguana/.gradle
      - ~/.vscode-server:/home/iguana/.vscode-server
      - ~/.vscode/extensions:/home/iguana/.vscode/extensions
      - ~/.ssh:/home/iguana/.ssh
      - .:/home/iguana/fatec-api-4

    restart: always

    links:
      - "postgres:database"

    ports:
      - 8080:8080
      - 3000:3000
    tty: true

  postgres:
    image: postgis/postgis

    restart: always

    environment:
      POSTGRES_DB: terravision
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

    ports:
      - 5433:5432
